### ISSUE TITLE
Integrate Auto Library

### ISSUE THREAD

**Issue by bhavinshah7** [graph-quilt/graphql-service-adapters#10]
Integrate [Auto Library](https://github.com/intuit/auto) with orchestrator to achieve the following:

* Calculate semantic version bumps from PRs
* Skip a release with the skip-release label
* Generate changelogs with headers, authors
* Use labels to create new changelog sections
* Generate a GitHub release

**Comment by jainrocks** [comment]
Please assign this to me.

**Comment by bhavinshah7** [comment]
@jainrocks done.

**Comment by jainrocks** [comment]
Thanks @bhavinshah7

**Comment by bhavinshah7** [comment]
@jainrocks you will need this info while setting up Auto: 
Owner/ServiceAccount: `https://github.com/graphquilt-svc`
email: `graphquilt@gmail.com`
I am giving you push access, so you can create a personal github token to set up Auto.

**Comment by jainrocks** [comment]
Sure, I will start working on this

**Comment by skodamarthi** [comment]
@bhavinshah7 Can I work on this?

**Comment by jainrocks** [comment]
I am already working on this :)

**Comment by jainrocks** [comment]
Raised a PR: https://github.com/graph-quilt/graphql-service-adapters/pull/11

I am facing one issue with the GH_Token
`✖  error     Received 404!

This usually because the GitHub token you're using doesn't have the correct permissions to the repo.

The token used with auto must have at least "write" permission to your repo (https://github.com/graphquilt-svc/https://github.com/graph-quilt/graphql-service-adapters (​​)) to create releases and labels.

You can check the permission for you token by running "auto info".

`

Getting the above error, can @bhavinshah7 / @ashpak-shaikh  please share the token or guide me in creating the same
